<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Soring,-searching,-and-counting" data-toc-modified-id="Soring,-searching,-and-counting-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Soring, searching, and counting</a></span><ul class="toc-item"><li><span><a href="#Sorting" data-toc-modified-id="Sorting-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>Sorting</a></span></li><li><span><a href="#Searching" data-toc-modified-id="Searching-1.2"><span class="toc-item-num">1.2&nbsp;&nbsp;</span>Searching</a></span></li><li><span><a href="#Counting" data-toc-modified-id="Counting-1.3"><span class="toc-item-num">1.3&nbsp;&nbsp;</span>Counting</a></span></li></ul></li></ul></div>

# Soring, searching, and counting

In [11]:
import numpy as np

## Sorting

Q1. Sort x along the second axis.

In [12]:
x = np.array([[1,4],[3,1]])
x.sort(axis=1)
print(x)

[[1 4]
 [1 3]]


Q2. Sort pairs of surnames and first names and return their indices. (first by surname, then by name).

In [15]:
surnames =    ('Hertz',    'Galilei', 'Hertz')
first_names = ('Heinrich', 'Galileo', 'Gustav')

surname_indices = np.argsort(surnames)
sorted_indices = np.argsort(surname_indices)

print(sorted_indices)

[1 0 2]


Q3. Get the indices that would sort x along the second axis.

In [16]:
x = np.array([[1,4],[3,1]])
sorted_indices = np.argsort(x, axis=1)
print(sorted_indices)

[[0 1]
 [1 0]]


Q4. Create an array such that its fifth element would be the same as the element of sorted x, and it divide other elements by their value.

In [23]:
x = np.random.permutation(10)
print(x)

sorted_indices = np.argsort(x)

new_array = np.zeros_like(x)
new_array[:4] = sorted_indices[:4]
new_array[4] = sorted_indices[4]
new_array[5:] = sorted_indices[5:]

print(new_array)

[1 5 6 9 3 4 8 0 2 7]
[7 0 8 4 5 1 2 9 6 3]


Q5. Create the indices of an array such that its third element would be the same as the element of sorted x, and it divide other elements by their value.

In [27]:
x = np.random.permutation(10)
print(x)

sorted_indices = np.argsort(x)

array = np.zeros_like(x)
array[:3] = sorted_indices[:3]
array[3] = sorted_indices[3]
array[4:] = sorted_indices[4:]
print(partitioned_array)

indices = np.argsort(array)
print(indices)

[8 7 3 2 1 5 9 6 4 0]
[3 5 2 7 6 4 9 0 1 8]
[8 7 3 2 1 5 9 6 4 0]


## Searching

Q6. Get the maximum and minimum values and their indices of x along the second axis.

In [28]:
x = np.random.permutation(10).reshape(2, 5)
print(x)

max_values = np.amax(x, axis=1)
max_indices = np.argmax(x, axis=1)

min_values = np.amin(x, axis=1)
min_indices = np.argmin(x, axis=1)

print("Maximum values:")
print(max_values)

print("Max indices:")
print(max_indices)

print("Minimum values:")
print(min_values)

print("Min indices:")
print(min_indices)


[[3 9 1 5 7]
 [2 8 6 4 0]]
Maximum values:
[9 8]
Max indices:
[1 1]
Minimum values:
[1 0]
Min indices:
[2 4]


Q7. Get the maximum and minimum values and their indices of x along the second axis, ignoring NaNs.

In [29]:
x = np.array([[np.nan, 4], [3, 2]])

max_values = np.nanmax(x, axis=1)
max_indices = np.nanargmax(x, axis=1)

min_values = np.nanmin(x, axis=1)
min_indices = np.nanargmin(x, axis=1)

print("Maximum values ignoring NaNs:")
print(max_values)

print("Maximum indices:")
print(max_indices)

print("Minimum values ignoring NaNs:")
print(min_values)

print("Minimum indices :")
print(min_indices)


Maximum values ignoring NaNs:
[4. 3.]
Maximum indices:
[1 0]
Minimum values ignoring NaNs:
[4. 2.]
Minimum indices :
[1 1]


Q8. Get the values and indices of the elements that are bigger than 2 in x.


In [31]:
x = np.array([[1, 2, 3], [1, 3, 5]])

values_greater_than_2 = x[x > 2]
indices_greater_than_2 = np.where(x > 2)

print("Values bigger than 2:")
print(values_greater_than_2)

print("Their indices are:")
print(indices_greater_than_2)


Values bigger than 2:
[3 3 5]
Their indices are:
(array([0, 1, 1], dtype=int64), array([2, 1, 2], dtype=int64))


Q9. Get the indices of the elements that are bigger than 2 in the flattend x.

In [39]:
x = np.array([[1, 2, 3], [1, 3, 5]])
indices = np.arange(x.size)
print(indices)

[0 1 2 3 4 5]


Q10. Check the elements of x and return 0 if it is less than 0, otherwise the element itself.

In [40]:
x = np.arange(-5, 4).reshape(3, 3)
result = np.where(x < 0, 0, x)
print(result)

[[0 0 0]
 [0 0 0]
 [1 2 3]]


Q11. Get the indices where elements of y should be inserted to x to maintain order.

In [41]:
x = np.array([1, 3, 5, 7, 9])
y = np.array([0, 4, 2, 6])

indices = np.searchsorted(x, y)
print(indices)

[0 2 1 3]


## Counting

Q12. Get the number of nonzero elements in x.

In [42]:
x = np.array([[0, 1, 7, 0, 0], [3, 0, 0, 2, 19]])

nonzero_count = np.count_nonzero(x)
print(nonzero_count)

5
